### PR TITLE
Project 4 building with backgrounds and gradients

### PR DESCRIPTION
**Pull request by afcastaneda223**
Microverse project  #4 building with backgrounds and gradients.

### CODE REVIEW

**Review by fatymahmed — COMMENTED** [review]
## Hi @afcastaneda223, 
 Your project looks good 👏, however, there are a few things that you need to fix

- The main content should have an image set as background, [see screenshot from Odin](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_image_requirement.png). You can use `background-image` orl `background-url` in your CSS to place the image.
- Bottom
 It contains four elements which are links, you already have the four elements above the footer, please change them to become links just like in the apple page.

- Your footer looks good, please wrap it using `<footer>` tags.
- Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store) [see the screenshot of the requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png). You've committed DS_Store file, please fix this.

- According to the requirements, you should check your markup file with a validator for any errors [see the screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png), You have an error on your markup file, please fix it. 
screenshot of the error

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Please make the suggested changes and request for another code review.
## Status: Changes Required
_Feel free to reach out to me on slack (fatima) if you have any questions, I'd be happy to help 😃._

**Review by fatymahmed — COMMENTED** [review]
## Hi @afcastaneda223,
I noticed that you've made some changes according to the previous review, great job👏👏.
However, for this project to be approved, you need to make all changes.

Please refer to my previous review for a detailed review, but here are some of the things that you haven't changed but you should.
- The main content should have an image set as background, [see the screenshot from Odin](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_image_requirement.png).
 You can use `background-image` or `background-url` in your CSS to place the image.
 This means you can't have the image in the HTML file, rather define it using either of the 2 ways in your CSS file.

- Bottom
It contains four elements which are links, you already have the four elements above the footer, please change them to become links just like in the apple page.
These are the ones with "iPhone 5S", "iPhone 5C", "Happy Birthday Mac" and "Supplier responsibility" content.

- Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store) [see the screenshot of the requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png). You've committed DS_Store 
file, please remove them.

[OPTIONAL]
- You could change the color of the text in the search field so that it's visible, right now I can't see anything when I type.

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Please make the suggested changes and request for another code review.
## Status: Changes Required
_Feel free to reach out to me on slack (fatima) if you have any questions, I'd be happy to help 😃._

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @afcastaneda223  , 👋 You have done a great job in this project 👏 

>Please refer to my previous review for a detailed review, but here are some of the things that you haven't changed but you should.

- [ ] The main content should have an image set as background, [see the screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_image_requirement.png) from Odin.
- [ ] You can use background-image or background-url in your CSS to place the image.
- [ ] This means you can't have the image in the HTML file, rather define it using either of the 2 ways in your CSS file.

Bottom

- [ ] It contains four elements which are links, you already have the four elements above the footer, please change them to become links just like in the apple page.
- [ ] These are the ones with "iPhone 5S", "iPhone 5C", "Happy Birthday Mac" and "Supplier responsibility" content.

- [ ] .gitignore unwanted files, assets/.DS_Store, and DS_store in css folder
- [ ] [optional] change the title of the project in readme.
----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

**Review by imhta — COMMENTED** [review]
### @afcastaneda223 Still previous code review requirements not fulfilled. So kindly fix those issues and then request for another code review.

**Comment by afcastaneda223** [comment]
they are fixed, please review the code:

Screen Shot 2020-01-15 at 11 48 24 AM
Screen Shot 2020-01-15 at 11 48 00 AM

**Comment by afcastaneda223** [comment]
the main image is on the css with background image, 

the images are contained in <a href"#> so they are links as requested

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi @afcastaneda223 ! Nice job doing the requested changes :100: 

## Project approved.


* Great that you use nav & footer tags, but think about to use [main](https://www.w3schools.com/tags/tag_main.asp) tag for the dominant content of the <body> of a document in your next project.

Go ahead and merge to master.
Goodluck in your next project Happy coding

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
